sudo: false

language: go

services:
  - docker

go:
  - 1.9

env:
  - DOCKER_IMAGE=pragkent/hydra-wework:0.8.1

script:
  - set -e
  - make test
  - make docker-bin
  - docker build -t $DOCKER_IMAGE .
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker push $DOCKER_IMAGE
